### PR TITLE
add 2 notebooks that use the new ml slc cge

### PR DESCRIPTION
**Pull request by Rashmil-1999**
Please test and run the new notebooks after you've installed the ml slc cge branch with core.

### CODE REVIEW

**Review by ywkim312 — APPROVED** [review]
both notebook worked okay

**Comment by ywkim312** [comment]
I approved but github action failed so please check to fix it

**Review by navarroc — CHANGES_REQUESTED** [review]
These notebooks should be linked in the manual in manual_jb/content/notebooks_other.md. I would put them under the analyses section.

**Comment by Rashmil-1999** [comment]
@navarroc  I have added the entry. Does it look good?

**Review by navarroc — APPROVED** [review]

**Pull request merged**
