### PR TITLE
Fixes #401 - added buyout decision analysis documentation

### LINKED ISSUE #401: Add buyout model analysis documentation and example notebook
This is related to https://github.com/IN-CORE/pyincore/issues/539. We should document the analysis and add an example notebook.

### PR DESCRIPTION
**Pull request by navarroc**
- [x] added buyout decision documentation
- [x] added buyout decision example notebook

### CODE REVIEW

**Comment by navarroc** [comment]
Example notebook is being completed. Please review the documentation to make sure it all looks right. Thanks!

**Comment by navarroc** [comment]
Everything is ready for review now

**Review by longshuicy — APPROVED** [review]
The notebook requires seaborn but never uses it 
```
import seaborn as sns
```
Everything else looks good.

**Comment by navarroc** [comment]
> The notebook requires seaborn but never uses it
> 
> ```
> import seaborn as sns
> ```
> 
> Everything else looks good.

I'll remove it.

**Comment by navarroc** [comment]
I removed the unused import and validated the notebook runs without issue.

**Pull request merged**
