### PR TITLE
35 Add retrofit notebook and zip file to tutorials

### PR DESCRIPTION
**Pull request by ncsa-mo**

### CODE REVIEW

**Review by nunezco2 — APPROVED** [review]

**Comment by ncsa-mo** [comment]
We can start reviewing the notebook. There will be minor changes in text later on but other than that it is ready.

**Comment by jonglee1** [comment]
Can we add Yunjie's email address?

**Comment by jonglee1** [comment]
Can we ask Yunjie for better description at the beginning? What this tutorial is about?

**Comment by ncsa-mo** [comment]
I updated her Affiliation as well

**Review by longshuicy — APPROVED** [review]
notebook runs well. Approving.

Only question would be do we need to include the .csv in the repo?

**Review by jonglee1 — APPROVED** [review]

**Comment by ncsa-mo** [comment]
I think so for csv, we need two input csv files

**Pull request merged**
