### PR TITLE
557 rename monte carlo failure probability to monte carlo limit state probability docs

### PR DESCRIPTION
**Pull request by longshuicy**
Work with this PR: https://github.com/IN-CORE/pyincore/pull/576

### CODE REVIEW

**Comment by navarroc** [comment]
Can you fix the name in the markdown file name? mc_lmit_state_prob.md should be mc_limit_state_prob.md

**Comment by longshuicy** [comment]
> Can you fix the name in the markdown file name? mc_lmit_state_prob.md should be mc_limit_state_prob.md

Sorry I should've been more careful. Fixed it now :-)

**Comment by navarroc** [comment]
The _toc.yml file needs to be updated (monte carlo analysis is missing from this file), which controls the analyses shown in the side panel of the manual.

**Comment by navarroc** [comment]
I'm not sure if it's related to this PR or if something merged wrong, but I see this when I build the manual:

Screenshot from 2024-06-06 16-33-16

**Comment by navarroc** [comment]
> I'm not sure if it's related to this PR or if something merged wrong, but I see this when I build the manual:
> 
> Screenshot from 2024-06-06 16-33-16

ahh, I think maybe we just forgot to remove the old reference.

**Comment by longshuicy** [comment]
> The _toc.yml file needs to be updated (monte carlo analysis is missing from this file), which controls the analyses shown in the side panel of the manual.

fixed

**Comment by longshuicy** [comment]
> > I'm not sure if it's related to this PR or if something merged wrong, but I see this when I build the manual:
> > Screenshot from 2024-06-06 16-33-16
> 
> ahh, I think maybe we just forgot to remove the old reference.

I think it might got carried over from the building non-structural PR. Also fixed.

**Comment by longshuicy** [comment]
> > I'm not sure if it's related to this PR or if something merged wrong, but I see this when I build the manual:
> > Screenshot from 2024-06-06 16-33-16
> 
> ahh, I think maybe we just forgot to remove the old reference.

Wait maybe we should remove it....you are right

**Review by navarroc — APPROVED** [review]
Looks good

**Pull request merged**
