### PR TITLE
fixed galvaston dfr3 view in notebook

### PR DESCRIPTION
**Pull request by ywkim312**
The plotting of dfr3 in this one only works in dev now. However, it should work after dfr3 are deployed in prod.

### CODE REVIEW

**Comment by navarroc** [comment]
I think you need to fix it in the zip file too.

**Comment by ywkim312** [comment]
> I think you need to fix it in the zip file too.

that was what I asked in slack. I will do it.

**Comment by navarroc** [comment]
Also, you need to fix it inside manual_jb not manual.

**Comment by ywkim312** [comment]
> Also, you need to fix it inside manual_jb not manual.

yes I will do when I fix zip file

**Comment by navarroc** [comment]
> > I think you need to fix it in the zip file too.
> 
> that was what I asked in slack. I will do it.

Sorry if I missed it.

**Comment by ywkim312** [comment]
> > > I think you need to fix it in the zip file too.
> > 
> > 
> > that was what I asked in slack. I will do it.
> 
> Sorry if I missed it.

no problem :)

**Review by navarroc — APPROVED** [review]

**Review by ncsa-mo — APPROVED** [review]

**Pull request merged**
