### PR TITLE
add workshop files

### LINKED ISSUE #62: Add latest workshop agenda and notebooks

### PR DESCRIPTION
**Pull request by ncsa-mo**
close #62

### CODE REVIEW

**Comment by navarroc** [comment]
A few things I noticed:
1. When you click expand IN-CORE workshops on the side bar, it only shows the May workshop in the side menu
2. If I click on IN-CORE Workshops, the Lifeline workshop only has an active link for Session 2
3. If I click on the 2022-01-31 Agenda link, it shows me all the sessions. However, Session 1 - Jupyter Introduction link doesn't render the notebook. It just goes to a blank page

**Comment by navarroc** [comment]
Looking further, it looks like we need to update _toc.yml to include an entry for the lifelines workshop and update workshops/20220131/agenda.md to have the title "Lifelines workshop". Then it will show up in the side menu under IN-CORE Workshops

> A few things I noticed:
> 
> 1. When you click expand IN-CORE workshops on the side bar, it only shows the May workshop in the side menu
> 2. If I click on IN-CORE Workshops, the Lifeline workshop only has an active link for Session 2
> 3. If I click on the 2022-01-31 Agenda link, it shows me all the sessions. However, Session 1 - Jupyter Introduction link doesn't render the notebook. It just goes to a blank page

**Comment by ncsa-mo** [comment]
I fixed the toc file and updated links to pdf files

**Review by navarroc — APPROVED** [review]
Looks good.

**Review by diegoac2 — APPROVED** [review]

**Pull request merged**
