### PR TITLE
Combined wind, wave, surge building damage

### PR DESCRIPTION
**Pull request by navarroc**
Combined wind, wave, surge building damage documentation

### CODE REVIEW

**Review by nunezco2 — APPROVED** [review]

**Comment by ywkim312** [comment]
I had a error in combined_bldg_dmg.run_analysis()
I tested it with installing the latest develop branch. Maybe I should install other branch?

```
ValueError                                Traceback (most recent call last)
<ipython-input-11-0d1b7ed4ab33> in <module>
      5 combined_bldg_dmg.set_input_dataset("flood_damage", flood_damage)
      6 combined_bldg_dmg.set_parameter("result_name", result_name)
----> 7 combined_bldg_dmg.run_analysis()

c:\virtualenv\pyincore\lib\site-packages\pyincore\baseanalysis.py in run_analysis(self)
    290                 return result
    291 
--> 292         return self.run()
    293 
    294     def run(self):

c:\virtualenv\pyincore\lib\site-packages\pyincore\analyses\combinedwindwavesurgebuildingdamage\combinedwindwavesurgebuildingdamage.py in run(self)
     31         flood_damage = self.get_input_dataset("flood_damage").get_dataframe_from_csv()
     32 
---> 33         wind_max_damage = DataProcessUtil.get_max_damage_state(wind_damage)
     34         wind_max_damage.rename(columns={'max_state': 'w_max_ds', 'max_prob': 'w_maxprob'}, inplace=True)
     35 

c:\virtualenv\pyincore\lib\site-packages\pyincore\utils\dataprocessutil.py in get_max_damage_state(dmg_result)
    257             dmg_states = ["ds-none", "ds-slight", "ds-moderat", "ds-extensi", "ds-complet"]
    258         else:
--> 259             raise ValueError("Invalid damage state names. Cannot create mapped max damage state.")
    260 
    261         guids = dmg_result[['guid']]

ValueError: Invalid damage state names. Cannot create mapped max damage state.
```

**Comment by navarroc** [comment]
> I had a error in combined_bldg_dmg.run_analysis() I tested it with installing the latest develop branch. Maybe I should install other branch?
> 
> ```
> ValueError                                Traceback (most recent call last)
> <ipython-input-11-0d1b7ed4ab33> in <module>
>       5 combined_bldg_dmg.set_input_dataset("flood_damage", flood_damage)
>       6 combined_bldg_dmg.set_parameter("result_name", result_name)
> ----> 7 combined_bldg_dmg.run_analysis()
> 
> c:\virtualenv\pyincore\lib\site-packages\pyincore\baseanalysis.py in run_analysis(self)
>     290                 return result
>     291 
> --> 292         return self.run()
>     293 
>     294     def run(self):
> 
> c:\virtualenv\pyincore\lib\site-packages\pyincore\analyses\combinedwindwavesurgebuildingdamage\combinedwindwavesurgebuildingdamage.py in run(self)
>      31         flood_damage = self.get_input_dataset("flood_damage").get_dataframe_from_csv()
>      32 
> ---> 33         wind_max_damage = DataProcessUtil.get_max_damage_state(wind_damage)
>      34         wind_max_damage.rename(columns={'max_state': 'w_max_ds', 'max_prob': 'w_maxprob'}, inplace=True)
>      35 
> 
> c:\virtualenv\pyincore\lib\site-packages\pyincore\utils\dataprocessutil.py in get_max_damage_state(dmg_result)
>     257             dmg_states = ["ds-none", "ds-slight", "ds-moderat", "ds-extensi", "ds-complet"]
>     258         else:
> --> 259             raise ValueError("Invalid damage state names. Cannot create mapped max damage state.")
>     260 
>     261         guids = dmg_result[['guid']]
> 
> ValueError: Invalid damage state names. Cannot create mapped max damage state.
> ```

The latest develop branch should have the new analysis. Also, did you use the "dev" settings I put in a comment on this PR? This will not run with production yet.

**Comment by ywkim312** [comment]
> > I had a error in combined_bldg_dmg.run_analysis() I tested it with installing the latest develop branch. Maybe I should install other branch?
> > ```
> > ValueError                                Traceback (most recent call last)
> > <ipython-input-11-0d1b7ed4ab33> in <module>
> >       5 combined_bldg_dmg.set_input_dataset("flood_damage", flood_damage)
> >       6 combined_bldg_dmg.set_parameter("result_name", result_name)
> > ----> 7 combined_bldg_dmg.run_analysis()
> > 
> > c:\virtualenv\pyincore\lib\site-packages\pyincore\baseanalysis.py in run_analysis(self)
> >     290                 return result
> >     291 
> > --> 292         return self.run()
> >     293 
> >     294     def run(self):
> > 
> > c:\virtualenv\pyincore\lib\site-packages\pyincore\analyses\combinedwindwavesurgebuildingdamage\combinedwindwavesurgebuildingdamage.py in run(self)
> >      31         flood_damage = self.get_input_dataset("flood_damage").get_dataframe_from_csv()
> >      32 
> > ---> 33         wind_max_damage = DataProcessUtil.get_max_damage_state(wind_damage)
> >      34         wind_max_damage.rename(columns={'max_state': 'w_max_ds', 'max_prob': 'w_maxprob'}, inplace=True)
> >      35 
> > 
> > c:\virtualenv\pyincore\lib\site-packages\pyincore\utils\dataprocessutil.py in get_max_damage_state(dmg_result)
> >     257             dmg_states = ["ds-none", "ds-slight", "ds-moderat", "ds-extensi", "ds-complet"]
> >     258         else:
> > --> 259             raise ValueError("Invalid damage state names. Cannot create mapped max damage state.")
> >     260 
> >     261         guids = dmg_result[['guid']]
> > 
> > ValueError: Invalid damage state names. Cannot create mapped max damage state.
> > ```
> 
> The latest develop branch should have the new analysis. Also, did you use the "dev" settings I put in a comment on this PR? This will not run with production yet.

Oops sorry. I will test with dev setting

**Comment by ywkim312** [comment]
> client = IncoreClient("https://incore-dev.ncsa.illinois.edu")
> hazard_id = "5fa472033c1f0c73fe81461a"
> bldg_dataset_id = "63053e74c8f8b7614f6cff9f" # Dev

I have only read the top comment... my bad

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
