### PR TITLE
339 Add galveston community app notebook with retrofit

### PR DESCRIPTION
**Pull request by Vismayak**

### CODE REVIEW

**Comment by ywkim312** [comment]
Can you update changelog?

**Comment by ywkim312** [comment]
please fix the conflict

**Comment by ywkim312** [comment]
I got this error ```ERROR - http_util.py:return_http_response() - A HTTPError has occurred 
HTTP Status code: 404
Error Message: Could not find the dataset 65dcf904c013b927b93bf632```

**Comment by ywkim312** [comment]
I got an error from following cell
```
ret_json = DataProcessUtil.create_mapped_dmg_result_gal(
    bldg_gdf, combined_dmg_retrofit_df_rs, arch_mapping, "max_state", "arch_wind"
)
ret_json
```
the error is 
```
AttributeError                            Traceback (most recent call last)
Cell In[14], line 1
----> 1 ret_json = DataProcessUtil.create_mapped_dmg_result_gal(
      2     bldg_gdf, combined_dmg_retrofit_df_rs, arch_mapping, "max_state", "arch_wind"
      3 )
      4 ret_json

AttributeError: type object 'DataProcessUtil' has no attribute 'create_mapped_dmg_result_gal'
```

**Review by navarroc — CHANGES_REQUESTED** [review]
This notebook should be linked in the manual in manual_jb/content/notebooks_other.md. I would put them under the analyses section.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
