### PR TITLE
Added traffic flow recovery analysis documentation and example notebook

### PR DESCRIPTION
**Pull request by ywkim312**
Please test a newly added notebook after installing following pyincore PR

https://github.com/IN-CORE/pyincore/pull/570

### CODE REVIEW

**Review by navarroc — CHANGES_REQUESTED** [review]
You changed the output key of the new traffic flow analysis so the transportation_recovery.ipynb needs to be fixed. It's using the old output key "overall_transportation_recovery_trajectory"

**Comment by navarroc** [comment]
Can you also add a reference in the analyses.md file? Otherwise the new analysis doesn't show up in the analyses page of the manual.

**Comment by ywkim312** [comment]
> Can you also add a reference in the analyses.md file? Otherwise the new analysis doesn't show up in the analyses page of the manual.

Sorry I missed it. Added

**Comment by ywkim312** [comment]
> You changed the output key of the new traffic flow analysis so the transportation_recovery.ipynb needs to be fixed. It's using the old output key "overall_transportation_recovery_trajectory"

So should I also update the existing transportation recovery notebook to point to the renamed analysis? I thought the old notebook just remained untouched and would be removed eventually? So, you mean, I have to keep the old notebook but the notebook should point to renamed analysis? Or maybe I am misunderstanding?

**Comment by navarroc** [comment]
> > You changed the output key of the new traffic flow analysis so the transportation_recovery.ipynb needs to be fixed. It's using the old output key "overall_transportation_recovery_trajectory"
> 
> So should I also update the existing transportation recovery notebook to point to the renamed analysis? I thought the old notebook just remained untouched and would be removed eventually? So, you mean, I have to keep the old notebook but the notebook should point to renamed analysis? Or maybe I am misunderstanding?

Since you deprecated instead of renaming, we should keep the old notebook for now and just fix the key so the notebook works. When we officially remove the old analysis, then we can delete the notebook.

**Comment by ywkim312** [comment]
> > > You changed the output key of the new traffic flow analysis so the transportation_recovery.ipynb needs to be fixed. It's using the old output key "overall_transportation_recovery_trajectory"
> > 
> > 
> > So should I also update the existing transportation recovery notebook to point to the renamed analysis? I thought the old notebook just remained untouched and would be removed eventually? So, you mean, I have to keep the old notebook but the notebook should point to renamed analysis? Or maybe I am misunderstanding?
> 
> Since you deprecated instead of renaming, we should keep the old notebook for now and just fix the key so the notebook works. When we officially remove the old analysis, then we can delete the notebook. I don't think you need to make the old notebook use the new analysis. You can leave that part as-is.

Pushed the notebook with new key

**Review by longshuicy — APPROVED** [review]

**Pull request merged**
