### PR TITLE
Fixes #380 - upgraded version of Jupyter Book to 0.15.1

### LINKED ISSUE #380: Upgrade jupyter book to version 0.15.1
From a quick test, it looks like we can go to the latest jupyter book before the 1.0 release, version 0.15.1, without any breaking changes. There is an issue to upgrade to 1.0 here, which we should investigate later: #379

In the meantime, we should upgrade to the latest before the 1.0 to pull in newer features than our current version 0.13.2.

### PR DESCRIPTION
**Pull request by navarroc**
Upgraded version of Jupyter Book to 0.15.1. Also changed the Dockerfile to pull in python 3.9. Please check to make sure things are working correctly (links, etc). I tried going to version 1.0, but there are some breaking changes so I rolled back to the latest before 1.0. I opened an issue to look into 1.0 later.

### CODE REVIEW

**Review by ylyangtw — COMMENTED** [review]
I updated the version in README.

Sorry I couldn't build the container for some reason... I have tried `RUN pip install --upgrade pip` in the Dockerfile still didn't get any luck... 
Here is the error log, it didn't say much
```
------
Dockerfile:12
--------------------
  10 |     COPY requirements.txt /src/
  11 |     RUN pip install --upgrade pip
  12 | >>> RUN python3 -m pip install -r requirements.txt
  13 |     
  14 |     COPY content/ /src/content/
--------------------
ERROR: failed to solve: process "/bin/sh -c python3 -m pip install -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by navarroc** [comment]
> I updated the version in README.
> 
> Sorry I couldn't build the container for some reason... I have tried `RUN pip install --upgrade pip` in the Dockerfile still didn't get any luck... Here is the error log, it didn't say much
> 
> ```
> ------
> Dockerfile:12
> --------------------
>   10 |     COPY requirements.txt /src/
>   11 |     RUN pip install --upgrade pip
>   12 | >>> RUN python3 -m pip install -r requirements.txt
>   13 |     
>   14 |     COPY content/ /src/content/
> --------------------
> ERROR: failed to solve: process "/bin/sh -c python3 -m pip install -r requirements.txt" did not complete successfully: exit code: 1
> ```

Did you try building with no cache (it's in the readme)

Another possibility, try changing python3 to python and see if that fixes it for your platform. You shouldn't need to, but maybe you can try that for testing. If it works, please don't push that change since it shouldn't be needed. I'm just suggesting it to see if you can build the docker to view the changes.

**Comment by ylyangtw** [comment]
I have tried cache/no cache, neither of them work. python didn't work either. It may be just my local env problem. 

I have tried pulling the image from the hub, the jupyter book works fine.

**Review by ylyangtw — APPROVED** [review]

**Comment by ywkim312** [comment]
I have deployed this PR to incore-dev. Please navigate around.

**Review by ywkim312 — APPROVED** [review]
Tested links and most links looks good

**Review by longshuicy — APPROVED** [review]
Works for me

**Pull request merged**
