### PR TITLE
Create notebook for network dataset generation

### PR DESCRIPTION
**Pull request by ywkim312**
Please test this notebook after installing pyincore PR https://github.com/IN-CORE/pyincore/pull/174
This notebook will post the dataset to prod. So please remove the posted dataset after testing the notebook
At the very end of the notebook, it will give you the new dataset id generated
You can remove the dataset in prod instance's data viewer. https://incore.ncsa.illinois.edu/DataViewer

### CODE REVIEW

**Comment by ywkim312** [comment]
@jonglee1 @longshuicy The error has been fixed and the client has been switched to prod.

**Comment by navarroc** [comment]
This needs to have develop merged in and you need to add a link from manual_jb/content/notebooks_other.md so this example is available from the incore documentation.

**Comment by longshuicy** [comment]
I got an error: 
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [10], in <cell line: 20>()
     17 out_graph_filename = 'network_graph.csv'
     19 # create output link shapefile and graph file
---> 20 NetworkUtil.build_dataset_by_line(link_filename, link_id_field, fromnode_field, tonode_field, out_node_filename, out_graph_filename)

AttributeError: type object 'NetworkUtil' has no attribute 'build_dataset_by_line'
```

**Review by navarroc — CHANGES_REQUESTED** [review]
This needs to have develop merged in and you need to add a link from manual_jb/content/notebooks_other.md so this example is available from the incore documentation.

**Comment by ywkim312** [comment]
> This needs to have develop merged in and you need to add a link from manual_jb/content/notebooks_other.md so this example is available from the incore documentation.

resolved

**Comment by ywkim312** [comment]
> I got an error:
> 
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> Input In [10], in <cell line: 20>()
>      17 out_graph_filename = 'network_graph.csv'
>      19 # create output link shapefile and graph file
> ---> 20 NetworkUtil.build_dataset_by_line(link_filename, link_id_field, fromnode_field, tonode_field, out_node_filename, out_graph_filename)
> 
> AttributeError: type object 'NetworkUtil' has no attribute 'build_dataset_by_line'
> ```

fixed it

**Review by navarroc — CHANGES_REQUESTED** [review]
Can you also update the _toc.yml file? There is a tutorials section there that if you don't update it, then there is no link from the side menu. The list of tutorials starts around line 53 of _toc.yml in manual_jb/content

**Comment by ywkim312** [comment]
> Can you also update the _toc.yml file? There is a tutorials section there that if you don't update it, then there is no link from the side menu. The list of tutorials starts around line 53 of _toc.yml in manual_jb/content

Oh did not know about that. Thank you for letting me know. Updated.

**Comment by navarroc** [comment]
Should this set the data type as incore:EPNnetwork and not incore:network?

**Comment by ywkim312** [comment]
> incore:EPNnetwork

Updated to incore:EPNnetwork

**Review by navarroc — CHANGES_REQUESTED** [review]
You need to add a link to the zip file at the bottom of tutorials.md. The link won't work until we release this, but it should be:

- Create Network Dataset: [create_network_dataset.zip](https://github.com/IN-CORE/incore-docs/blob/main/notebooks/create_network_dataset.zip)

**Comment by longshuicy** [comment]
Dont forget changelog

**Review by longshuicy — APPROVED** [review]

**Review by navarroc — APPROVED** [review]

**Pull request merged**
