### PR TITLE
190 add salt lake city cge analysis documentation

### PR DESCRIPTION
**Pull request by longshuicy**

### CODE REVIEW

**Review by nunezco2 — APPROVED** [review]

**Comment by Rashmil-1999** [comment]
Screenshot 2023-03-08 at 4 09 32 PM

I get this error saying `KeyError: "['HS3_R1', 'HS3_R2'] not in index"`

**Comment by Rashmil-1999** [comment]
Do I need to do anything else as well as a part of the setup?

**Comment by navarroc** [comment]
I think we need to update this with the 2 regions data

**Comment by longshuicy** [comment]
> I think we need to update this with the 2 regions data

fixed

**Comment by navarroc** [comment]
We might need to upload an example shocks file for 2 regions. This doesn't converge for me with the current inputs.

**Comment by navarroc** [comment]
@longshuicy I added a 2 regions example sector shocks to production if you want to use it in this notebook. I tested this with your notebook and it works:

640a203218fd3853fb31efd7

**Review by navarroc — APPROVED** [review]

**Pull request merged**
