### PR TITLE
Fixes #387 - added gas facility damage analysis documentation and example notebook

### LINKED ISSUE #387: Add gas facility damage example notebook and documentation
- Add documentation for gas facility damage analysis
- Add example jupyter notebook for gas facility damage analysis

### PR DESCRIPTION
**Pull request by navarroc**
- Added gas facility damage analysis documentation page
- Added example notebook

### CODE REVIEW

**Comment by navarroc** [comment]
This needs to be tested with https://github.com/IN-CORE/pyincore/pull/574

**Review by ywkim312 — COMMENTED** [review]
Just asking, it doesn't need to update _toc, right?

**Comment by navarroc** [comment]
> Just asking, it doesn't need to update _toc, right?

You are correct, let me fix that!

**Comment by navarroc** [comment]
> > Just asking, it doesn't need to update _toc, right?
> 
> You are correct, let me fix that!

fixed!

**Review by ywkim312 — APPROVED** [review]

**Pull request merged**
