### PR TITLE
131 create a mmsa pipeline functionality notebook

### PR DESCRIPTION
**Pull request by longshuicy**
ready to be reviewed

### CODE REVIEW

**Review by nunezco2 — APPROVED** [review]

**Comment by navarroc** [comment]
Since this is a new analysis, you need to link it from content/analyses.md

**Comment by navarroc** [comment]
You also need to link the example notebook from content/notebooks_other.md

**Comment by navarroc** [comment]
You also need to add the new analysis to _toc.yml in manual_jb/content/_toc.yml

**Review by navarroc — CHANGES_REQUESTED** [review]
This needs a few files updated so the documentation is linked correctly.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
