### PR TITLE
510 bldg functionality column renaming docs

### PR DESCRIPTION
**Pull request by longshuicy**
Test this with PR  https://github.com/IN-CORE/pyincore/pull/511

### CODE REVIEW

**Review by ylyangtw — APPROVED** [review]
Ran 2 Joplin_testbed, galveston_community_app, building_func. All work well. Changes look good.

**Comment by ywkim312** [comment]
The following cell
```
# merge building geodataframe with output
bldg_func_gdf = bldg_gdf.merge(df_bldg_func, on='guid')
```
made this error
```
KeyError: 'guid'
```

**Comment by ywkim312** [comment]
in galveston_community_app.ipynb's 
```
ret_json = DataProcessUtil.create_mapped_dmg_result_gal(
    bldg_gdf, combined_dmg_df_rs, arch_mapping, "max_state", "arch_wind"
)
ret_json
```
I got following error
```
AttributeError: type object 'DataProcessUtil' has no attribute 'create_mapped_dmg_result_gal'
```

**Review by ywkim312 — APPROVED** [review]
All the notebooks ran successfully. Approve

**Pull request merged**
