### PR TITLE
336 refactoring inspire workshop for hazarddatasets

### PR DESCRIPTION
**Pull request by longshuicy**
- Fixed the workshop session 2 and session 3. Please run session 2 and 3 to check
- Update the workshop zip file
- Reran create eq and create tornado notebook so the correct "hazardDatasets" are showing in the cell

### CODE REVIEW

**Comment by navarroc** [comment]
Can you clear the output in create_earthquake.zip? I think that was missed when it was created and it shows the old rasterDataset in the output cell

**Comment by navarroc** [comment]
Rest of this looks good

**Comment by longshuicy** [comment]
> Can you clear the output in create_earthquake.zip? I think that was missed when it was created and it shows the old rasterDataset in the output cell

Updated that zip file

**Review by navarroc — APPROVED** [review]

**Review by ylyangtw — APPROVED** [review]
session 2 & 3 work well. approving

**Pull request merged**
